# 使用官方 Node.js LTS 镜像作为基础镜像
FROM node:16.20.2

# 创建并设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json (如果有) 到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 全局安装 Hardhat
RUN npm install -g hardhat

# 复制项目文件到工作目录
COPY . .

# 暴露应用端口（如果需要）
EXPOSE 8545

# 默认命令，进入一个 shell，可以根据需要修改
CMD [ "npx","hardhat" ]
